
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.1  Build: September 30th, 2011
-- Firebird 1.5/2.x DDL Script generated from project: AdventureWorks
-- Project filename: C:\Projects\NetIndustry\LlblGenTraining\AdventureWorks\AdventureWorks.Dal\AdventureWorks.llblgenproj
-- Script generated on: 11-Dec-2011 22:55.35
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Default' 
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- DROP sequences for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Default'
-- ----------------------------------------------------------------------------------------------------------------

-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE "AwbuildVersion"
(
	"DatabaseVersion" VARCHAR(25) NOT NULL, 
	"ModifiedDate" DATE NOT NULL, 
	"VersionDate" DATE NOT NULL 
);

CREATE TABLE "DatabaseLog"
(
	"DatabaseLogId" INTEGER NOT NULL, 
	"DatabaseUser" VARCHAR(128) NOT NULL, 
	"Event" VARCHAR(128) NOT NULL, 
	"Object" VARCHAR(128), 
	"PostTime" DATE NOT NULL, 
	"Schema" VARCHAR(128), 
	"Tsql" BLOB SUB_TYPE 1 NOT NULL, 
	"XmlEvent" BLOB SUB_TYPE 1 NOT NULL 
);

CREATE TABLE "Department"
(
	"DepartmentId" SMALLINT NOT NULL, 
	"GroupName" VARCHAR(50) NOT NULL, 
	"ModifiedDate" DATE NOT NULL, 
	"Name" VARCHAR(50) NOT NULL 
);

CREATE TABLE "Employee"
(
	"BirthDate" DATE NOT NULL, 
	"ContactId" INTEGER NOT NULL, 
	"EmployeeId" INTEGER NOT NULL, 
	"Gender" VARCHAR(1) NOT NULL, 
	"HireDate" DATE NOT NULL, 
	"LoginId" VARCHAR(256) NOT NULL, 
	"ManagerId" INTEGER, 
	"MaritalStatus" VARCHAR(1) NOT NULL, 
	"ModifiedDate" DATE NOT NULL, 
	"NationalIdnumber" VARCHAR(15) NOT NULL, 
	"SickLeaveHours" SMALLINT NOT NULL, 
	"Title" VARCHAR(50) NOT NULL, 
	"VacationHours" SMALLINT NOT NULL 
);

CREATE TABLE "EmployeeAddress"
(
	"AddressId" INTEGER NOT NULL, 
	"EmployeeId" INTEGER NOT NULL, 
	"ModifiedDate" DATE NOT NULL 
);

CREATE TABLE "ErrorLog"
(
	"ErrorLine" INTEGER, 
	"ErrorLogId" INTEGER NOT NULL, 
	"ErrorMessage" VARCHAR(4000) NOT NULL, 
	"ErrorNumber" INTEGER NOT NULL, 
	"ErrorProcedure" VARCHAR(126), 
	"ErrorSeverity" INTEGER, 
	"ErrorState" INTEGER, 
	"ErrorTime" DATE NOT NULL, 
	"UserName" VARCHAR(128) NOT NULL 
);
-- -------[ Sequences ]--------------------------------------------------------------------------------------------

CREATE GENERATOR "SEQ_DatabaseLog";

CREATE GENERATOR "SEQ_Employee";

CREATE GENERATOR "SEQ_ErrorLog";

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints and Unique constraints
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Default'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Default'
-- ----------------------------------------------------------------------------------------------------------------
